### ISSUE TITLE
eg-sampler crashes

### ISSUE THREAD

**Issue by olijaun** [lv2/lv2#44]
Hi

I'm a complete beginner to audio plugin programming... So I studied your examples and I wanted to run the sampler. Unfortunately I get no sound and when I click on "Request Sample" my DAW crashes. I tried with ardour5 and ardour6 (rc1). The eg-amp works without any issues. I tried with master which seems to be equal to 1.18.0.

Update: I've just tried with Carla which gives some more information each time I click on the play button:

```
Unknown port event format
Warning: LV2 UI sending atom with invalid size 12! size: 11, padded-size: 16
```

Thanks and Regards
Oliver

**Comment by drobilla** [comment]
Older versions of Ardour made the mistake of implementing that feature before it was finalized, so I'd expect crashes there, but I am not sure how the RC releases line up.  I've only tested with relatively recent master and Jalv.  IIRC @falkTX tested it with Carla as well.

The above message is because of padding I guess.  The size of the valid atom data is 11, but the buffer is 12.  It should be fixed by 7fb5846, thanks.

**Comment by olijaun** [comment]
Hi
Thanks a lot for your quick response and fix!
Unfortunately I'm still not getting any sound from the plugin.

- carla: no sound (the message I mentioned above disappeared with your fix)
- ardour v5: no sound, crashes when clicking on "request sample"
- ardour v6 (rc1): no sound, crashes when clicking on "request sample"
- qtractor: no sound, crashes when clicking on "request sample"

I noticed that I have quite an old version of lv2 on my system (1.14.0~dfsg1-2 on ubuntu). So I compiled the latest lv2 and installed it to /usr/local

I also compiled and installed jalv. The eg-sampler also crashed with jalv as soon as I press "request sample".

As it seems to work for you with jalv there must be some other problem. Although I think it is strange because many other plugins work without problems.

Any ideas? Thanks a lot.
Regards
Oliver

**Comment by olijaun** [comment]
OK, latest news... I compiled the recently released ardour 6.0! With this version it does not crash anymore. I think that the crashing has something to do with the UI. I get crashes with jalv.gtkmm when I press on "request sample". With gtk3 there is no such button.

So this crash aside I'd like to hear some sound. I can change the samples e.g. with jalv.gtk3 and the waveform image changes. But I cannot hear anything, whether the click.wav nor any own sample.

So I (naivly) added the following to line 326 of sample.c:

```
printf("midi message: %i \n", lv2_midi_message_type(msg));
```

just before the switch. When I run this it keeps printing "midi message: 0". I does not matter whether I press the play button of the plugin or if I press a key on my midi keyboard. It is always "0".

**Comment by drobilla** [comment]
That's... odd.

Great detective work though, thanks.  I'll look into it.

**Comment by olijaun** [comment]
geat, thanks. just keep in mind that I'm a complete beginner. so it might be just me as well :-)

**Comment by olijaun** [comment]
OK, found the problem.

I compared it with the x42-midifilter plugins. Then I found the following. The lv2 example plugins (eg-sampler, eg-fifths and maybe more) do the following to get the MIDI message:

```
const uint8_t* const msg = (const uint8_t*)LV2_ATOM_BODY_CONST(ev);
```
which seems to result in something like this:
```
const uint8_t* const msg = ((const void*)((const uint8_t*)(ev) + sizeof(LV2_Atom)));
```
However this does not work. lv2_midi_message_type(msg) always returns 0 for such messages. In the x42-midifilter plugins the following is done:
```
const uint8_t* const msg = ((const void*)((const uint8_t*)(ev+1)));
```
And this works! I was able to get eg-fifth and eg-sampler running with this change!

So although I almost don't dare to say it... but it seems there is a bug in the LV2_ATOM_BODY_CONST macro...??? Or is there something else going on?

**Comment by drobilla** [comment]
Ah.  This is a bug from 3aad5eb1b08ed5c27e60aa36021c4a85ce90c08f.  `ev` is not an atom.

**Comment by olijaun** [comment]
Ok. So it's not a bug in LV2_ATOM_BODY_CONST but in the examples. Now that I know what's causing the problem it's fine for me. However I think you should revert the mentioned commit in order for others that want to learn LV2 because the example is part of the "lv2-book" (in the book it's actually correct I noticed).
Thanks for your help.
Regards
Oliver

**Comment by drobilla** [comment]
Simply reverted for now 001234d
